name: "Deploy Terraform stacks in Development"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Development Terraform
    uses: ukhsa-collaboration/devops-github-reusable-workflows/.github/workflows/terraform-plan-apply.yml@v3.1.0
    concurrency:
      group: "dev-main"
    permissions:
      packages: read
      contents: read
      security-events: write
      statuses: write
      checks: write
      id-token: write
    with:
      environment_name: dev
      execute_terraform_plan: true
    secrets:
      # Github environments would be better here but can't be used in
      # UKHSA-Collobration because it's a Free-tier organisation.
      AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID_DEV }}"
      AWS_ROLE_NAME: "${{ secrets.AWS_ROLE_NAME }}" 
      TF_PLAN_ENCRYPTION_PASSPHRASE: "${{ secrets.TF_PLAN_ENCRYPTION_PASSPHRASE }}"