name: "Run scheduled destroy job"
on:
  schedule:
    - cron: '0 19 * * 1-5' # Every weekday at 19:00

jobs:
  destroy:
    name: Destroy Development Terraform
    uses: ukhsa-collaboration/devops-github-reusable-workflows/.github/workflows/terraform-destroy.yml@main
    permissions:
      packages: read
      contents: read
      security-events: write
      statuses: write
      checks: write
      id-token: write
    with:
      environment_name: dev
      execute_terraform_plan: true
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
      TF_MODULES_SSH_DEPLOY_KEY: ${{ secrets.TF_MODULES_SSH_DEPLOY_KEY }}